// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqratyohahdtcrkxkqbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcmF0eW9oYWhkdGNya3hrcWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDc2OTUsImV4cCI6MjA1NzQ4MzY5NX0.PTN-2vDqfERsX6OjFuemdc7oD3MhyJH4OBh7da7sius";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);